services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: smakthe/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3001:80"